### ISSUE TITLE
Is there a way to pass `insecureHTTPParser` configuration to request?

### ISSUE THREAD

**Issue by Overtorment** [ladjs/frisbee#105]
Because of Incapsula CDN some requests are broken on latest nodejs (cli). Luckily it works ok in RN (and probably in browser).
Error that is thrown by frisbee:

```
FetchError {
      message: 'request to ... failed, reason: Parse Error: Invalid header value char',
      type: 'system',
      errno: 'HPE_INVALID_HEADER_TOKEN',
      code: 'HPE_INVALID_HEADER_TOKEN'
    } 
```

https://github.com/nodejs/node/issues/27711

Workaround is to pass `--insecure-http-parser` to nodejs cli.

related: https://nodejs.org/api/cli.html#cli_insecure_http_parser

**Comment by niftylettuce** [comment]
On the server-side yes, just pass `insecureHTTPParser: Boolean` see <https://github.com/node-fetch/node-fetch#options>.

Let me know if that works for you.

**Comment by niftylettuce** [comment]
See previous comment.  We use `cross-fetch/polyfill`, which then uses `node-fetch`, which I previously shared a link to configuration options for (which are inherited).

**Comment by Overtorment** [comment]
that did not work for me.

I tried:


```

this._api = new Frisbee({ baseURI: this.baseURI });

// ...


    const response = await this._api.get('/api/v1/offers?' + uri.join('&'), {
      insecureHTTPParser: true,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Content-Type': 'application/json',
      },
    });
```

PS. tried to pass as an option to constructor as well, no luck

**Comment by Overtorment** [comment]
fyi, still no luck passing that config the way you showed, but what worked is:

`NODE_OPTIONS=--insecure-http-parser=true ./node_modules/.bin/jest  tests/integration/mytest.test.js  `
